[build]
  publish = "."
  command = "echo 'static site - FINAL A + Cjenik + Full Admin'"

[[redirects]]
  from = "/admin/*"
  to = "/admin/index.html"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/public/js/*"
  [headers.values]
    Cache-Control = "no-cache"