[build]
  publish = "."
  command = "echo 'static site - FINAL SECURE ADMIN - cjenik 100/80/30'"

[[redirects]]
  from = "/admin/*"
  to = "/admin/index.html"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/admin/*"
  [headers.values]
    Cache-Control = "no-cache"
    X-Frame-Options = "DENY"

[[headers]]
  for = "/public/js/*"
  [headers.values]
    Cache-Control = "no-cache"
